[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
anyhow = "1.0.68"
log = "0.4.17"
pollster = "0.2.5"
simple_logger = "4.0.0"
wgpu = "0.14.2"
winit = "0.27.5"
